[workspace]
types = "app/src/idl/"

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fame = "3u8R4PRxhPTVNsGpGmzchZM1A3viTnyvZLTEzQjTE9q6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keys/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
