[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
fame = "6MKdszXxg1V2E5E9ofXqov467arq5wCQUSSJETas2XHN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./keys/test.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
